name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install --upgrade pip pyinstaller
    - run: pip install -r requirements.txt
    - run: pyinstaller *.spec
    - uses: actions/upload-artifact@v3
      with:
        name: exe
        path: dist/
